5.10. Микросетки на флексах для всех страниц
htmlacademy-htmlcss/177781-device-32 pull request #7
Opened 2021-11-06 17:15 UTC by yu2v

2021-11-07 13:39 UTC, andreysgra requested changes

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +  left: 60px;
1. Нужно задать размеры ссылки равными размеру изображения. Иначе сейчас можно кликнуть по всей этой области
![image](https://user-images.githubusercontent.com/17790771/140646132-f44068c9-7bc6-48bf-b9cb-fe4be411ffcc.png)
2. Если позиционировать логотип, то тогда уж абсолютно, так как относительное позиционирование влияет на окружающие элементы.

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +  height: 300px;
Для `header-container` правильнее использовать `min-height`, так как в блоке есть контент, количество которого может варьироваться.

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +  left: 263px;
Здесь нет необходимости в относительном позиционировании. Достаточно первый пункт списка сделать флекс контейнером
![image](https://user-images.githubusercontent.com/17790771/140646358-4338be3d-910a-4ab0-901f-6892cac99ba9.png)

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +  top: -150px;
Можно вполне обойтись без относительного позиционирования, если посмотреть немного под иным углом.
Это границы хэдера
![image](https://user-images.githubusercontent.com/17790771/140646564-4f3b508b-3f69-4abe-b37f-2d9bba43c275.png)
а это границы слайдера
![image](https://user-images.githubusercontent.com/17790771/140646598-7cf979e5-9f46-42b9-aaf1-e0e4641ce4ec.png)
У обоих заливка градиентная: у хэдера от белого к жёлтому, у слайдера от жёлтого к белому (чтобы переходы были резкими, а не плавными, нужно задать значение, где заканчивается первый цвет равным значению, там где начинается второй цвет. Например `background-image: linear-gradient(180deg,#f7e296 110px,#fff 110px);`).

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +  border: black 1px solid;
Не нужно задавать ключевые слова для обозначения цвета.

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +}
В этом блоке флекс совершенно не нужен.

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +  margin-bottom: 53px;
Относительное позиционирование слайдера влияет на окружение и вам приходится также смещать нижележащие блоки, что делает вёрстку не универсальной. Если вы пересмотрите подход, на тот, что я описал выше, то вам не понадобится смещать эти блоки.

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +
Опять же, дынным кнопкам
![image](https://user-images.githubusercontent.com/17790771/140647070-29f5cbe4-34a6-40a7-b434-0bf7bda90d10.png)
нужно абсолютное, а не относительное позиционирование.

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +  margin-bottom: 70px;
Если пересмотрите подход к вёрстке слайдера, то отрицательный сдвиг не понадобится.

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +  background: linear-gradient(to top, #f0f0f0 75%, white 0%);
Не нужно задавать ключевые слова для обозначения цвета.

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +  width: 1094px;
А разве есть какой-то смысл в том, чтобы ограничивать ширину этого блока?

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +}
`margin-top: -2px;` - какая-то ненужная подгонка.

2021-11-07 13:39 UTC, andreysgra commented on css/styles.css
> +}
Не проще ли поменять в разметке местами блоки
![image](https://user-images.githubusercontent.com/17790771/140647279-de46a8eb-5d3b-40c0-a4e7-63852005c51a.png)
чем менять их порядок с помощью `order: -1`?

К тому же, слайды `tab-content` стоит объединить под одной общей обёрткой. Тогда в родительском блоке `services-tabs` будет всего 2 блока: этот и `services-tabs-buttons`. Чем меньше блоков, тем проще управлять их раскладкой.

2021-11-08 17:01 UTC, yu2v commented on css/styles.css
> +  top: -150px;
off top, не понимаю почему flex набирают пиксели, на примере слайдера, макс высота по макету должна быть 560 но из за flex-сов слайдер набирает еще 10px не понимаю как это исправить?(пока поставил max-height: 560px чтобы соответствовать шаблону)

2021-11-08 17:49 UTC, yu2v commented on css/styles.css
> +
Я руководствовался тем, что при абсолютном позиционировании, при изменении масштаба страницы в браузере, кнопки уезжают

2021-11-08 17:51 UTC, yu2v commented on css/styles.css
> +  margin-bottom: 53px;
тут не совсем понял, как мне сдвинуть .slider-part  и как на него в нахлест навести .slide-title

2021-11-09 08:33 UTC, andreysgra commented on css/styles.css
> +  top: -150px;
Чтобы разобраться в проблеме лучше всего исследовать вёрстку в dev tools.
Мы видим, что высота слайда `slider-item` больше, чем высота блока `slider`
![image](https://user-images.githubusercontent.com/17790771/140887501-04abd386-de92-473f-91bc-e1571ea7e36a.png)
Переходим в блок `slider-item-img` и наблюдаем ту же картину - высота `slider-item-img` больше высоты `slider`. Похоже, что проблема где-то здесь. Внутри блока `slider-item-img` находится только изображение. По умолчанию у тега `img` значение свойства `display` равно `inline`, то есть `img` ведёт себя, как строчный элемент. Перевод строки в HTML (невидимый символ) добавляется сразу после `img` и получается зазор между родительским блоком `slider-item-img` и изображением. Этот зазор увеличивает высоту `slider-item-img`. Высота соседнего блока `slider-part-item` становится равной высоте блока `slider-item-img` за счёт того, что во флекс контейнере значение свойства `align-items` по умолчанию равно `stretch`.

Решение проблемы: добавить `display: block` изображению `slider-image`.

2021-11-09 08:36 UTC, andreysgra commented on css/styles.css
> +  margin-bottom: 53px;
Здесь придётся использовать абсолютное позиционирование для `slider-part` (и нужно не забыть про `z-index`).

2021-11-09 08:37 UTC, andreysgra commented on css/styles.css
> +
Всё зависит от того, к каким координатам привязывать абсолютно позиционированный элемент. Возможно у вас проблема была из-за этого.

2021-11-09 08:38 UTC, merged