6.17. Постройте мелкие сетки на гридах для подходящих компонентов
htmlacademy-htmlcss/177781-device-32 pull request #8
Opened 2021-11-13 18:32 UTC by yu2v

немного потерялся в последовательности выполнения заданий.

2021-11-14 17:22 UTC, andreysgra requested changes

2021-11-14 17:22 UTC, andreysgra commented on css/styles.css
> +  left: 510px;
Позиционировать лучше не отдельно взятые кнопки, а их обёртку `.slider-button--container`. Тогда обёртка за счёт контента обретёт высоту. Сейчас её высота равна 0.
![image](https://user-images.githubusercontent.com/17790771/141690671-576eb391-d3a1-46f0-b0d6-689908b90e95.png)

2021-11-14 17:22 UTC, andreysgra commented on index.html
> +            </span>
Это всё лишние элементы разметки. Отмеченные блоки нужно реализовать через `::before` и `::aftre`
![image](https://user-images.githubusercontent.com/17790771/141690814-423a3115-613e-4fcc-a73d-f1df939a792a.png)

2021-11-14 17:22 UTC, andreysgra commented on css/styles.css
> +}
Цвет фона на самом деле изменяется не только у жёлтого блока с автомобилем, но и у всей ссылке. Посмотрите внимательнее стайлгайд.

2021-11-14 17:22 UTC, andreysgra commented on css/styles.css
> +}
На примере этого элемента поясню на счёт стилей для фокуса. Свойство `border` увеличивает геометрию элемента (на то она и рамка). Соответственно сдвигается нижележащий контент.
Высота ссылки в состоянии покоя:
![image](https://user-images.githubusercontent.com/17790771/141691070-5839a9d3-6f54-4b64-bdfe-a5e415390bad.png)
Высота ссылки в фокусе:
![image](https://user-images.githubusercontent.com/17790771/141691093-b6e8c7d2-ca6b-4c95-92f9-4c3805c5e0c8.png)

Поэтому для изображения фокуса лучше использовать свойство `outline`, которое не влияет на геометрию элемента.

И ещё один момент, если элемент попадает в фокус когда пользователь перешёл на него с клавиатуры, то мы видим, что поверх вашей обводки есть ещё и чёрная рамка
![image](https://user-images.githubusercontent.com/17790771/141691205-d3cf8111-945a-49eb-89a4-2c3ad397d9bc.png)
Современные браузеры используют стили для `:focus-visible`, поэтому лучше стили фокуса писать для этого псевдо класса, а не для `:focus`. Но если писать для `:focus`, то нужно тогда переопределять стили для свойства `outline`.

2021-11-14 17:22 UTC, andreysgra commented on css/styles.css
> +  margin: auto;
Здесь можно обойтись без абсолютного позиционирования. Для этого нужно изменить значение свойства `display` ссылки `class="footer-social--link"` на `block` и выровнять иконку по центру ссылки с помощью свойств `justify-content`и `align-items`.

2021-11-15 18:28 UTC, yu2v commented on css/styles.css
> +}
Про outline классное решение)
Про :focus-visible не знал,(в голове был вопрос по фокус через tab)
Кстати outline корректно работает и для :focus лишних очертаний нет

2021-11-15 18:28 UTC, yu2v commented on css/styles.css
> +}
поправлю когда пойму всю конструкцию данного элемента. Сейчас не понимаю как правильно сделать

2021-11-15 18:29 UTC, yu2v commented on index.html
> +            </span>
Не могу понять как svg код вставить в CSS, т.к. из лайвов я понял что если элементы меняют свое состояние то svg код нужно ставить в разметку.
Тут у нас получается 3 элемента могут менять состояние.
Картинка с машиной, текст ссылки и картинка с иконкой i причем они должны быть единым целым при наведении, на сколько я понял.

2021-11-15 19:28 UTC, andreysgra commented on index.html
> +            </span>
Для первого изображения
![image](https://user-images.githubusercontent.com/17790771/141842116-90468c19-7cf3-483f-a1b8-1165de8d8ed2.png)
Для второго
![image](https://user-images.githubusercontent.com/17790771/141842166-1432c0c1-59fa-4bd2-838d-8d36c3efe474.png)

2021-11-15 19:29 UTC, merged